### PR TITLE
added Dijkstras algorithm

### PR DESCRIPTION
**Pull request by vinay72**
I have added the Dijkstra's Algorithm in your Project. #51

### CODE REVIEW

**Comment by Rizzen** [comment]
Thank you for you PR! But we are accepting algorithms in programming languages, not in pseudocode, not descriptions of algorithms.

**Comment by vinay72** [comment]
You have not described this is issue?

**Comment by Rizzen** [comment]
It's described in contributing.md

**Comment by vinay72** [comment]
Okkay

**Pull request closed without merging**
